[mcp_servers."t2i-kamui-imagen4-ultra"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2i/fal/imagen4/ultra", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2i-kamui-qwen-image"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2i/fal/qwen-image", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2i-kamui-wan-v2-2-a14b"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2i/fal/wan/v2.2-a14b/text-to-image", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-aura-sr"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/aura-sr", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-flux-kontext-lora"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/flux/kontext", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-flux-kontext-max"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/flux/kontext/max", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-flux-krea-lora"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/flux-krea-lora/image-to-image", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-ideogram-character-remix"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/ideogram/character-remix", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2i-kamui-qwen-image-edit"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2i/fal/qwen/image-edit", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2v-kamui-veo3"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2v/fal/veo3", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2v-kamui-veo3-fast"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2v/fal/veo3/fast", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2v-kamui-wan-v2-2-5b-fast"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2v/fal/wan/v2.2-5b/text-to-video/fast-wan", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2v-kamui-wan-v2-2-a14b"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2v/fal/wan/v2-2-a14b", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."t2v-kamui-kling-video-v25-turbo-pro"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/t2v/fal/kling-video/v25-turbo-pro", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-decart-lucy-14b"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/decart/lucy-14b", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-hailuo-02-fast"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/minimax/hailuo-02/fast", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-hailuo-02-pro"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/minimax/hailuo-02/pro", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-kling-video-v25-turbo-pro"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/kling-video/v25-turbo-pro", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-omnihuman"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/bytedance/omnihuman", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true

[mcp_servers."i2v-kamui-seedance-v1-lite"]
command = "npx"
args = ["mcp-remote", "https://kamui-code.ai/i2v/fal/bytedance/seedance-v1-lite", "--transport", "http-only", "--header", "KAMUI-CODE-PASS: kamui_Dpcha0qsvsuvbrdieb7Br8Bse3ufxPBNiNrDdJXokZk"]
timeout = 10000
trust = true
